version: 0.2

phases:
  install:
    runtime-versions:
      java: corretto21
    commands:
      - echo Installing dependencies...

  build:
    commands:
      - echo Build started on `date`
      - mvn clean package
      - echo Build completed on `date`

artifacts:
  files:
    - target/*.jar
  discard-paths: yes